import {
  BULLET_MASS_KG,
  GAS_SPEED_MS,
  MUZZLE_SPEED,
  POWDER_MASS_KG,
  RIFLE_MASS_KG,
} from './constants';

export const BULLET_MOMENTUM = BULLET_MASS_KG * MUZZLE_SPEED;
export const GAS_MOMENTUM = POWDER_MASS_KG * GAS_SPEED_MS;
export const TOTAL_MOMENTUM = BULLET_MOMENTUM + GAS_MOMENTUM;
export const RECOIL_SPEED = TOTAL_MOMENTUM / RIFLE_MASS_KG;
export const GAS_SHARE = GAS_MOMENTUM / TOTAL_MOMENTUM;
