import type { MaterialFinish } from '@core/scene/materials';
import { THEME } from '../theme';

const GLOSS_REFLECTION = 1.6;
const METAL_REFLECTION = 1.3;
const LAMP_GLOW = 0.6;
const GLASS_REFLECTION = 2.2;
const CELL_REFLECTION = 0.8;
const DIODE_GLOW = 1.4;
const LED_GLOW = 2.2;
const DIAGRAM_GLOW = 0.35;
const JUNCTION_GLOW = 0.9;

function diagram(color: string, glow = DIAGRAM_GLOW): MaterialFinish {
  return { color, emissive: color, emissiveIntensity: glow, roughness: 0.85, metalness: 0 };
}

export const PAINT = {
  plaster: '#dccbb0',
  concrete: '#bdb7ac',
  coping: '#d2cdc3',
  plinth: '#8f877b',
  paver: '#c4bdb0',
  paverJoint: '#978f83',
  windowFrame: '#f3f3f0',
  windowGlass: '#27394d',
  door: '#4d6670',
  steel: '#9aa1a8',
  darkSteel: '#5a6169',
  pvc: '#a3a8ad',
  lamp: '#fff0cc',
  lampGlow: '#ffd98a',
  frame: THEME.frame,
  cell: '#18224a',
  cellEdge: '#0f1530',
  cellRear: '#8b9097',
  fingerLine: 'rgba(205, 214, 232, 0.22)',
  busbar: '#d5d9de',
  ribbon: '#dfe2e6',
  backsheet: '#eef0ef',
  encapsulant: '#f4f7f8',
  glass: THEME.glass,
  junctionBox: '#2a2d31',
  cable: '#1d1f22',
  connector: '#34373c',
  rail: '#b7bec6',
  ballast: '#a7a39b',
  cellGlow: '#ff4a1a',
  diodeOff: '#5b6068',
  diodeOn: '#ffb020',
  diodePlate: '#1b1e24',
  deadString: '#6b7280',
  inverter: '#eceef0',
  inverterFront: '#dfe3e7',
  meter: '#c7ccd1',
  meterCover: '#9ea5ad',
  screen: '#0d1a14',
  screenText: '#9dffb8',
  window: '#1a2430',
  ledGreen: THEME.good,
  ledRed: '#ff4d4d',
  ledOff: '#3a3f45',
  brand: THEME.sun,
  lawn: '#7c8c6c',
  pyramids: '#4f5fa6',
  arCoating: '#2a3290',
  emitter: '#9a4a60',
  junction: THEME.dusk,
  base: '#2b4678',
  rearPassivation: '#8fd3c8',
  rearContact: '#b9bec6',
  finger: '#eceff2',
  leader: '#f2f4f7',
} as const;

export const FINISHES = {
  plaster: { color: PAINT.plaster, roughness: 0.92, metalness: 0 },
  concrete: { color: PAINT.concrete, roughness: 0.95, metalness: 0 },
  coping: { color: PAINT.coping, roughness: 0.85, metalness: 0 },
  plinth: { color: PAINT.plinth, roughness: 0.95, metalness: 0 },
  windowFrame: { color: PAINT.windowFrame, roughness: 0.55, metalness: 0 },
  windowGlass: {
    color: PAINT.windowGlass,
    roughness: 0.08,
    metalness: 0.3,
    envMapIntensity: GLOSS_REFLECTION,
  },
  door: { color: PAINT.door, roughness: 0.5, metalness: 0.35 },
  steel: {
    color: PAINT.steel,
    roughness: 0.35,
    metalness: 0.8,
    envMapIntensity: METAL_REFLECTION,
  },
  darkSteel: { color: PAINT.darkSteel, roughness: 0.45, metalness: 0.6 },
  pvc: { color: PAINT.pvc, roughness: 0.6, metalness: 0 },
  lamp: {
    color: PAINT.lamp,
    emissive: PAINT.lampGlow,
    emissiveIntensity: LAMP_GLOW,
    roughness: 0.4,
    metalness: 0,
  },
  frame: {
    color: PAINT.frame,
    roughness: 0.3,
    metalness: 0.85,
    envMapIntensity: METAL_REFLECTION,
  },
  rail: { color: PAINT.rail, roughness: 0.4, metalness: 0.75, envMapIntensity: METAL_REFLECTION },
  ballast: { color: PAINT.ballast, roughness: 0.95, metalness: 0 },
  glass: {
    color: PAINT.glass,
    roughness: 0.04,
    metalness: 0.1,
    transparent: true,
    opacity: 0.16,
    depthWrite: false,
    envMapIntensity: GLASS_REFLECTION,
  },
  encapsulant: {
    color: PAINT.encapsulant,
    roughness: 0.6,
    metalness: 0,
    transparent: true,
    opacity: 0.28,
    depthWrite: false,
  },
  backsheet: { color: PAINT.backsheet, roughness: 0.7, metalness: 0 },
  cellFront: {
    color: '#ffffff',
    roughness: 0.55,
    metalness: 0.05,
    emissive: PAINT.cellGlow,
    emissiveIntensity: 0,
    envMapIntensity: CELL_REFLECTION,
  },
  cellEdge: { color: PAINT.cellEdge, roughness: 0.5, metalness: 0.1 },
  cellRear: { color: PAINT.cellRear, roughness: 0.6, metalness: 0.4 },
  busbar: {
    color: PAINT.busbar,
    roughness: 0.3,
    metalness: 0.9,
    polygonOffset: true,
    polygonOffsetFactor: -1,
  },
  ribbon: {
    color: PAINT.ribbon,
    roughness: 0.3,
    metalness: 0.85,
    polygonOffset: true,
    polygonOffsetFactor: -2,
  },
  junctionBox: { color: PAINT.junctionBox, roughness: 0.55, metalness: 0.05 },
  cable: { color: PAINT.cable, roughness: 0.6, metalness: 0 },
  connector: { color: PAINT.connector, roughness: 0.45, metalness: 0.1 },
  diodePlate: { color: PAINT.diodePlate, roughness: 0.6, metalness: 0 },
  diodeOff: { color: PAINT.diodeOff, roughness: 0.5, metalness: 0 },
  diodeOn: {
    color: PAINT.diodeOn,
    emissive: PAINT.diodeOn,
    emissiveIntensity: DIODE_GLOW,
    roughness: 0.4,
    metalness: 0,
  },
  lawn: { color: PAINT.lawn, roughness: 1, metalness: 0, transparent: true },
  inverter: { color: PAINT.inverter, roughness: 0.45, metalness: 0.05 },
  inverterFront: { color: PAINT.inverterFront, roughness: 0.4, metalness: 0.05 },
  meter: { color: PAINT.meter, roughness: 0.5, metalness: 0.05 },
  meterCover: { color: PAINT.meterCover, roughness: 0.55, metalness: 0.05 },
  window: { color: PAINT.window, roughness: 0.15, metalness: 0.2 },
  brand: { color: PAINT.brand, roughness: 0.5, metalness: 0 },
  ledOff: { color: PAINT.ledOff, roughness: 0.4, metalness: 0 },
  ledGreen: {
    color: PAINT.ledGreen,
    emissive: PAINT.ledGreen,
    emissiveIntensity: LED_GLOW,
    roughness: 0.4,
    metalness: 0,
  },
  ledRed: {
    color: PAINT.ledRed,
    emissive: PAINT.ledRed,
    emissiveIntensity: LED_GLOW,
    roughness: 0.4,
    metalness: 0,
  },
  pyramids: diagram(PAINT.pyramids),
  arCoating: diagram(PAINT.arCoating),
  emitter: diagram(PAINT.emitter),
  junction: diagram(PAINT.junction, JUNCTION_GLOW),
  base: diagram(PAINT.base),
  rearPassivation: diagram(PAINT.rearPassivation),
  rearContact: { color: PAINT.rearContact, roughness: 0.35, metalness: 0.8 },
  finger: { color: PAINT.finger, roughness: 0.25, metalness: 0.9 },
} as const satisfies Record<string, MaterialFinish>;

export type Finish = keyof typeof FINISHES;
