import { DoubleSide } from 'three';
import type { MaterialFinish } from '@core/scene/materials';
import { THEME } from '../theme';

const FLAME_GLOW = 1.1;
const CORE_GLOW = 1.5;
const CONTACT_GLOW = 0.45;
const DECAL_OFFSET = { polygonOffset: true, polygonOffsetFactor: -2, polygonOffsetUnits: -4 };

export const PAINT = {
  hullRed: '#8f3325',
  bootTop: '#2a2e33',
  hullGrey: '#c8ccc9',
  deck: '#6c7872',
  deckEdge: '#9aa1a4',
  trim: '#7d868c',
  white: '#e4e6e2',
  cream: '#e6e0cf',
  glass: '#253949',
  safetyYellow: '#f2c230',
  craneYellow: '#f3c63a',
  orange: '#ff7a1a',
  buoyancy: '#f08a2a',
  foam: '#f5ad63',
  steel: THEME.steel,
  stand: '#7c858c',
  darkSteel: '#474f56',
  black: '#1e2226',
  bopYellow: '#f0bd2c',
  podBlue: '#2f6fb8',
  bottle: '#c9ced3',
  containerBlue: '#3e6e9e',
  containerGreen: '#4f8a5b',
  containerRed: '#b5483b',
  mark: '#f4f4f0',
  topDrive: '#c9412f',
  conductor: '#4b5661',
  surfaceCasing: '#6f8092',
  intermediateCasing: '#9fb2c4',
  productionCasing: '#c9d5df',
  liner: '#dfe6ec',
  cement: '#d3c6a8',
  shoe: '#eef2f4',
  tubing: '#9fc0d4',
  packer: '#e2a33b',
  riser: '#b9c1c8',
  riserCut: '#e8ecef',
} as const;

export const FINISHES = {
  painted: { color: '#ffffff', vertexColors: true, metalness: 0.15, roughness: 0.62 },
  paintedMetal: { color: '#ffffff', vertexColors: true, metalness: 0.5, roughness: 0.42 },
  steel: { color: THEME.steel, metalness: 0.62, roughness: 0.4 },
  instanced: { color: '#ffffff', metalness: 0.45, roughness: 0.45 },
  pipe: {
    color: '#ffffff',
    vertexColors: true,
    metalness: 0.55,
    roughness: 0.38,
    flatShading: true,
  },
  collar: { color: '#7d868e', metalness: 0.6, roughness: 0.4, flatShading: true },
  hull: { color: PAINT.hullRed, metalness: 0.2, roughness: 0.62 },
  thruster: { color: '#ffffff', vertexColors: true, metalness: 0.35, roughness: 0.5 },
  crane: { color: '#ffffff', vertexColors: true, metalness: 0.2, roughness: 0.5 },
  lifeboat: { color: '#ffffff', vertexColors: true, metalness: 0.05, roughness: 0.5 },
  wire: { color: '#2e3338', metalness: 0.4, roughness: 0.6 },
  chain: { color: '#3c3a37', metalness: 0.5, roughness: 0.55 },
  mooringWire: {
    color: '#ffffff',
    vertexColors: true,
    metalness: 0.3,
    roughness: 0.6,
    transparent: true,
    depthWrite: false,
  },
  bop: { color: '#ffffff', vertexColors: true, metalness: 0.35, roughness: 0.5 },
  wellhead: { color: '#8e979f', metalness: 0.6, roughness: 0.4 },
  riser: { color: '#ffffff', vertexColors: true, metalness: 0.35, roughness: 0.5 },
  casing: { color: '#ffffff', vertexColors: true, metalness: 0.2, roughness: 0.6 },
  tubing: { color: '#ffffff', vertexColors: true, metalness: 0.5, roughness: 0.42 },
  bit: { color: '#ffffff', vertexColors: true, metalness: 0.6, roughness: 0.35 },
  hole: { color: '#4a423b', metalness: 0, roughness: 0.9, side: DoubleSide },
  mound: { color: '#a39b8e', metalness: 0, roughness: 1, flatShading: true },
  crack: { color: '#16120f', metalness: 0, roughness: 1, ...DECAL_OFFSET },
  tunnel: { color: '#120d09', metalness: 0, roughness: 1, ...DECAL_OFFSET },
  streak: {
    color: THEME.oil,
    metalness: 0.1,
    roughness: 0.35,
    transparent: true,
    opacity: 0.85,
    ...DECAL_OFFSET,
  },
  contact: {
    color: '#d8f1ff',
    emissive: '#8fd0ff',
    emissiveIntensity: CONTACT_GLOW,
    metalness: 0,
    roughness: 0.6,
    ...DECAL_OFFSET,
  },
  gasContact: {
    color: '#fff3c4',
    emissive: '#ffe08a',
    emissiveIntensity: CONTACT_GLOW,
    metalness: 0,
    roughness: 0.6,
    ...DECAL_OFFSET,
  },
  ruler: { color: '#f4f1e8', metalness: 0, roughness: 0.7, ...DECAL_OFFSET },
  sea: {
    color: '#177fb8',
    metalness: 0,
    roughness: 0.34,
    transparent: true,
    opacity: 0.5,
    depthWrite: false,
    side: DoubleSide,
    flatShading: true,
  },
  seaOuter: {
    color: '#177fb8',
    vertexColors: true,
    metalness: 0,
    roughness: 0.34,
    transparent: true,
    opacity: 0.5,
    depthWrite: false,
    side: DoubleSide,
  },
  cloud: {
    color: '#ffffff',
    vertexColors: true,
    emissive: '#c9d6e3',
    emissiveIntensity: 0.3,
    metalness: 0,
    roughness: 1,
    flatShading: true,
  },
  seaOpaque: { color: '#2a7fb0', metalness: 0, roughness: 0.35, flatShading: true },
  water: {
    color: '#ffffff',
    vertexColors: true,
    metalness: 0,
    roughness: 1,
    transparent: true,
    opacity: 0.42,
    depthWrite: false,
    side: DoubleSide,
  },
  waterOpaque: { color: '#ffffff', vertexColors: true, metalness: 0, roughness: 1 },
  flameOuter: {
    color: '#ff6a1f',
    emissive: '#ff5a14',
    emissiveIntensity: FLAME_GLOW,
    metalness: 0,
    roughness: 1,
    transparent: true,
    opacity: 0.8,
    depthWrite: false,
  },
  flameCore: {
    color: '#ffd36a',
    emissive: '#ffb640',
    emissiveIntensity: CORE_GLOW,
    metalness: 0,
    roughness: 1,
  },
} as const satisfies Record<string, MaterialFinish>;

export type Finish = keyof typeof FINISHES;

export const BAND_SURFACE = { metalness: 0, roughness: 0.92 } as const;

export const BAND_TONES = {
  seabed: '#817d69',
  claystone: '#8f7e6d',
  aquifer: '#b9b194',
  shaleSands: '#8a8378',
  seal: '#5c5f6d',
  gas: THEME.gas,
  oil: THEME.oil,
  water: THEME.brine,
  base: '#7e766c',
  sourceRock: '#3d3633',
} as const;
